version: '2'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/carriedb
      - SPRING_DATASOURCE_USERNAME=carrie
      - SPRING_DATASOURCE_PASSWORD=carrie
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysqldb

  mysqldb:
    image:   mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=carriedb
      - MYSQL_USER=carrie
      - MYSQL_PASSWORD=carrie
    ports:
      - "3306:3306"